### ISSUE TITLE
Add how-to instructions

### ISSUE THREAD

**Issue by simonbognoe** [kvnvelasco/ynab-commbank-csv#1]
Hey! Would love a small how-to instruction for this. Would love to use Commbank with YNAB in an easier way, and I'm new to Rust/Cargo.

**Comment by kvnvelasco** [comment]
Hello! Sorry to get back to this so late, this was just a toy i built for personal use. Glad to see it has some people with the same problem. 

I'll put up some instructions shortly.

**Comment by kvnvelasco** [comment]
@simonbognoe A readme has been put up.
